apiVersion: v1
kind: Service
metadata:
  name: {{ include "ifric-registry-service.postgresHost" . }}
  labels:
    {{- include "ifric-registry-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "ifric-registry-service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
