{{- if .Values.icid.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ifric-registry-service.icidHost" . }}
  labels:
    {{- include "ifric-registry-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: icid
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.icid.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ifric-registry-service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: icid
{{- end }}
